// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package postgresql

import (
	"time"
)

type OrdersLineItem struct {
	ID        int32  `json:"id"`
	OrderID   int32  `json:"order_id"`
	ProductID int32  `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	Price     string `json:"price"`
}

type OrdersOrder struct {
	OrderID    int32     `json:"order_id"`
	UserID     string    `json:"user_id"`
	OrderDate  time.Time `json:"order_date"`
	Amount     string    `json:"amount"`
	OrderState string    `json:"order_state"`
}

type OrdersProduct struct {
	ID          int32  `json:"id"`
	ProductName string `json:"product_name"`
	Price       string `json:"price"`
	Category    string `json:"category"`
}

type OrdersUser struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Passwd    string    `json:"passwd"`
	Email     string    `json:"email"`
	CreatedOn time.Time `json:"created_on"`
}
