// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
	"platform/cmd/order/config"
	"platform/internal/order/app/route"
	"platform/internal/order/eventHandle/handlers"
	"platform/internal/order/infras/grpc"
	"platform/internal/order/infras/mq"
	"platform/internal/order/infras/repo"
	"platform/internal/order/usecases/order"
	"platform/pkg/postgres"
	"platform/pkg/rabbitmq"
	"platform/pkg/rabbitmq/consumer"
	"platform/pkg/rabbitmq/publisher"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventConsumer, err := consumer.NewConsumer(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPublisher, err := publisher.NewPublisher(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userEventPublisher := mq.NewUserEventPublisher(eventPublisher)
	ordersRepo := repo.NewOrderRepo(dbEngine)
	userDomainService, err := infrasgrpc.NewGRPCUserClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	productDomainService, err := infrasgrpc.NewGRPCProductClient()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	useCase := order.NewService(ordersRepo, userDomainService, productDomainService, userEventPublisher)
	orderServiceServer := router.NewOrderGRPCServer(grpcServer, useCase)
	orderedDeletedEventHandler := handlers.NewOrderedEventHandlerImpl(useCase, userEventPublisher)
	app := New(cfg, dbEngine, connection, eventConsumer, userEventPublisher, ordersRepo, userDomainService, productDomainService, useCase, orderServiceServer, orderedDeletedEventHandler)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}
