app:
  name: 'user-service'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5001

order_client:
  url: 192.168.30.67:5004

logger:
  log_level: 'debug'
  rollbar_env: 'user-service'

rabbitmq:
  url: amqp://guest:guest@127.0.0.1:5672/